export { default as NotFoundImage } from './notFoundImage.svg'
export { default as NotFoundText } from './notFoundText.svg'
export { default as CurrentLevelMixIcon } from './currentLevelMixIcon.svg'
export { default as AllDecksMixIcon } from './allDeckMixIcon.svg'
export { default as Logo } from './logo.svg'
export {default as Cards} from './cards.svg'
export { default as OnbordingLine } from './onbordingLine.svg'
export { default as OnbordingLevels } from './onbordingLevels.svg'
export { default as OnbordingCards } from './onbordingCards.svg'
export { default as OnbordingPhone } from './onbordingPhone.svg'
export { default as OrangeFlower } from './orangeFlower.svg'
export { default as Flower } from './flower.svg'
